function x_twist = twist_solve_l0(A, b)

    %TwIST handles
    % Linear operator handles
    hR = @(x) A*x;
    hRt = @(x) A'*x;
    % define the regularizer and the respective denoising function
    Psi = @(x,th) hard(x,th);   % denoising function
    Phi = @(x) l0norm(x);       % regularizer

    %  regularization parameter
    tau = 20;

    % stopping theshold
    tolA = 1e-3;

    [x_twist,x_debias_twist,obj_twist,...
    times_twist,debias_start_twist,mse]= ...
         TwIST(b,hR,tau,...
         'Psi',Psi,...
         'Phi',Phi,...
         'AT', hRt, ...
         'Initialization',0,...
         'Monotone', 1, ...
         'StopCriterion',1,...
       	 'ToleranceA',tolA,...
         'Verbose', 1);

end