function x_twist = twist_solve_l1(A, b)

    %TwIST handles
    % Linear operator handles
    hR = @(x) A*x;
    hRt = @(x) A'*x;

    % regularization parameter
    tau = 0.0001;

    % TwIST parameters
    lambda1 = 0.0001;
    % stopping theshold
    tolA = 1e-5;

    % -- TwIST ---------------------------
    % stop criterium:  the relative change in the objective function
    % falls below 'ToleranceA'
    [x_twist,x_debias_twist,obj_twist,...
        times_twist,debias_start_twist,mse]= ...
             TwIST(b,hR,tau, ...
             'Lambda', lambda1, ...
             'Debias',0,...
             'AT', hRt, ...
             'Monotone',1,...
             'Sparse', 1,...
             'Initialization',0,...
             'StopCriterion',1,...
             'ToleranceA',tolA,...
             'Verbose', 1);

end